package gui;

import aplicacion.Categoria;
import java.util.List;

public class VCategorias extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;

    public VCategorias(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        initComponents();
        obligatorioTexto.setEnabled(false);
        ModeloListaStrings mListaCategorias = new ModeloListaStrings();
        lstCategorias.setModel(mListaCategorias);
        if (mListaCategorias.getSize() > 0) {
            lstCategorias.setSelectedIndex(0);
            btnBorrar.setEnabled(true);
        } else {
            btnBorrar.setEnabled(false);
        }
        this.fa = fa;
        this.BuscarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        CuadroNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAnhadir = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        obligatorioTexto = new javax.swing.JLabel();
        obligatorio1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CuadroDescripcion = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Categorías");

        jLabel8.setText("CATEGORÍAS:");

        CuadroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroNombreActionPerformed(evt);
            }
        });

        jLabel9.setText("Descripción:");

        jLabel10.setText("Nombre:");

        btnAnhadir.setText("Añadir");
        btnAnhadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhadirActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(180, 22, 45));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        obligatorioTexto.setForeground(new java.awt.Color(255, 0, 0));
        obligatorioTexto.setText("Rellena los campos obligatorios *");

        obligatorio1.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio1.setText("*");

        jScrollPane2.setViewportView(CuadroDescripcion);

        lstCategorias.setModel(new ModeloListaStrings());
        lstCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstCategorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(obligatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAnhadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(CuadroNombre))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(obligatorioTexto)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(obligatorioTexto)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CuadroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(obligatorio1))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnhadir)
                            .addComponent(btnBorrar))
                        .addGap(62, 62, 62)
                        .addComponent(btnSalir)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CuadroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuadroNombreActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAnhadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhadirActionPerformed
        AnhadirCategoria();
        ModeloListaStrings ma;
        ma = (ModeloListaStrings) lstCategorias.getModel();

        if ((CuadroNombre.getText() != null) && !(CuadroNombre.getText().isEmpty())) {
            ma.nuevoElemento(CuadroNombre.getText());
            lstCategorias.setSelectedIndex(ma.getSize() - 1);
            btnBorrar.setEnabled(true);
        }
    }//GEN-LAST:event_btnAnhadirActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        ModeloListaStrings m;

        m = (ModeloListaStrings) lstCategorias.getModel();
        String c = m.getElementAt(lstCategorias.getSelectedIndex());

        m.borrarElemento(lstCategorias.getSelectedIndex());
        fa.borrarCategoria(c);
        CuadroNombre.setText("");
        CuadroDescripcion.setText("");
        this.BuscarCategorias();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void lstCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCategoriasMouseClicked
        ModeloListaStrings m;
        List<Categoria> categorias = fa.obtenerCategoria(""); //Así obtengo todas las categorías y puedo settear la descripción

        m = (ModeloListaStrings) lstCategorias.getModel();
        String c = m.getElementAt(lstCategorias.getSelectedIndex());
        CuadroNombre.setText(c);
        for (Categoria cat : categorias) {
            if (cat.getNombre().equals(c)) {
                CuadroDescripcion.setText(cat.getDescripcion());
            }
        }
        btnBorrar.setEnabled(true);

    }//GEN-LAST:event_lstCategoriasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane CuadroDescripcion;
    private javax.swing.JTextField CuadroNombre;
    private javax.swing.JButton btnAnhadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstCategorias;
    private javax.swing.JLabel obligatorio1;
    private javax.swing.JLabel obligatorioTexto;
    // End of variables declaration//GEN-END:variables

    public void AnhadirCategoria() {
        if (CuadroNombre.getText().equals("")) {
            obligatorioTexto.setEnabled(true);
        } else {
            obligatorio1.setEnabled(false);
        }
        if (!CuadroNombre.getText().equals("")) {
            obligatorioTexto.setEnabled(false);
        }
        if (obligatorioTexto.isEnabled()) {
            return;
        }

        Categoria c;
        c = new Categoria(CuadroNombre.getText(), CuadroDescripcion.getText());
        fa.actualizarCategoria(c);
        CuadroNombre.setText("");
        CuadroDescripcion.setText("");
        this.BuscarCategorias();
    }

    public void BuscarCategorias() {
        ModeloListaStrings m = new ModeloListaStrings();
        List<Categoria> categorias = fa.obtenerCategoria(CuadroNombre.getText());
        lstCategorias.setModel(m);
        for (Categoria cat : categorias) {
            m.nuevoElemento(cat.getNombre());

        }
        if (m.getSize() > 0) {
            lstCategorias.setSelectedIndex(0);
        }
    }

}
