/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.util.Locale;
import javax.swing.JPanel;

/**
 *
 * @author alumnogreibd
 */
public class VParticipaciones extends javax.swing.JDialog {

    Color prueba = new Color(60, 63, 65);
    Color prueba1 = new Color(78, 82, 85);

    /**
     * Creates new form VParticipaciones
     */
    public VParticipaciones(aplicacion.FachadaAplicacion fa) {
        initComponents();
        this.getContentPane().setBackground(prueba);
        saldoText.setBackground(prueba1);
        jComboBox2.setBackground(prueba1);
        jComboBox1.setBackground(prueba1);
        nParticipacionesText.setBackground(prueba1);
        precioText.setBackground(prueba1);
        comisionText.setBackground(prueba1);
        carteraText.setBackground(prueba1);
        numeroText.setBackground(prueba1);
        compraventaPanel.setBackground(prueba);
        altabajaPanel.setBackground(prueba);
        jTable2.setBackground(prueba1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        participacionesPanel = new javax.swing.JTabbedPane();
        compraventaPanel = new javax.swing.JPanel();
        saldoLabel = new javax.swing.JLabel();
        saldoText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        nparticipacionesLabel = new javax.swing.JLabel();
        nParticipacionesText = new javax.swing.JTextField();
        precioLabel = new javax.swing.JLabel();
        comisionLabel = new javax.swing.JLabel();
        comisionText = new javax.swing.JTextField();
        precioText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        aceptarButton = new javax.swing.JButton();
        buscarButton = new javax.swing.JButton();
        altabajaPanel = new javax.swing.JPanel();
        carteraLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        carteraText = new javax.swing.JTextField();
        numeroText = new javax.swing.JTextField();
        altaCheckBox = new javax.swing.JCheckBox();
        bajaCheckBox = new javax.swing.JCheckBox();
        aceptarButton1 = new javax.swing.JButton();
        msjObligatorio = new java.awt.Label();
        msNoParticipaciones = new java.awt.Label();
        msSoloUnaOpcion = new java.awt.Label();
        btnSalir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        saldoLabel.setForeground(new java.awt.Color(187, 187, 188));
        saldoLabel.setText("saldo:");

        saldoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoTextActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(187, 187, 188));
        jLabel1.setText("€ ");

        jComboBox1.setForeground(new java.awt.Color(187, 187, 188));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setForeground(new java.awt.Color(187, 187, 188));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comprar", "Vender" }));

        nparticipacionesLabel.setForeground(new java.awt.Color(187, 187, 188));
        nparticipacionesLabel.setText("Número de participaciones:");

        nParticipacionesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nParticipacionesTextActionPerformed(evt);
            }
        });

        precioLabel.setForeground(new java.awt.Color(187, 187, 188));
        precioLabel.setText("Precio:");

        comisionLabel.setForeground(new java.awt.Color(187, 187, 188));
        comisionLabel.setText("Comisión:");

        precioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTextActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(187, 187, 188));
        jLabel2.setText("€ ");

        jLabel3.setForeground(new java.awt.Color(187, 187, 188));
        jLabel3.setText("%");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        aceptarButton.setText("Aceptar");

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout compraventaPanelLayout = new javax.swing.GroupLayout(compraventaPanel);
        compraventaPanel.setLayout(compraventaPanelLayout);
        compraventaPanelLayout.setHorizontalGroup(
            compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compraventaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(aceptarButton)
                        .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(compraventaPanelLayout.createSequentialGroup()
                                .addComponent(saldoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saldoText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(compraventaPanelLayout.createSequentialGroup()
                                .addComponent(nparticipacionesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nParticipacionesText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(compraventaPanelLayout.createSequentialGroup()
                                .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comisionLabel)
                                    .addComponent(precioLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comisionText)
                                    .addComponent(precioText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))))
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42))
        );
        compraventaPanelLayout.setVerticalGroup(
            compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compraventaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, compraventaPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saldoLabel)
                            .addComponent(saldoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nparticipacionesLabel)
                            .addComponent(nParticipacionesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(compraventaPanelLayout.createSequentialGroup()
                                .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(precioLabel)
                                    .addComponent(precioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comisionLabel))
                            .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comisionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(compraventaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarButton)
                    .addComponent(buscarButton))
                .addGap(27, 27, 27))
        );

        participacionesPanel.addTab("compra / venta", compraventaPanel);

        carteraLabel.setText("Cartera de participaciones:");

        numeroLabel.setText("Número de participaciones:");

        carteraText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carteraTextActionPerformed(evt);
            }
        });

        numeroText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTextActionPerformed(evt);
            }
        });

        altaCheckBox.setText("Alta");

        bajaCheckBox.setText("Baja");
        bajaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaCheckBoxActionPerformed(evt);
            }
        });

        aceptarButton1.setText("Aceptar");

        msjObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        msjObligatorio.setText("Rellena los campos obligatorios (*)");

        msNoParticipaciones.setForeground(new java.awt.Color(255, 0, 0));
        msNoParticipaciones.setText("No dispones de ese número de participaciones*");

        msSoloUnaOpcion.setForeground(new java.awt.Color(255, 0, 0));
        msSoloUnaOpcion.setText("Selecciona solo una opción *");

        javax.swing.GroupLayout altabajaPanelLayout = new javax.swing.GroupLayout(altabajaPanel);
        altabajaPanel.setLayout(altabajaPanelLayout);
        altabajaPanelLayout.setHorizontalGroup(
            altabajaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altabajaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(altabajaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(altabajaPanelLayout.createSequentialGroup()
                        .addComponent(msjObligatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceptarButton1))
                    .addGroup(altabajaPanelLayout.createSequentialGroup()
                        .addGroup(altabajaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(altabajaPanelLayout.createSequentialGroup()
                                .addComponent(carteraLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(carteraText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(msNoParticipaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(altabajaPanelLayout.createSequentialGroup()
                        .addGroup(altabajaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(altabajaPanelLayout.createSequentialGroup()
                                .addComponent(altaCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bajaCheckBox))
                            .addComponent(numeroLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(altabajaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(altabajaPanelLayout.createSequentialGroup()
                                .addComponent(numeroText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE))
                            .addGroup(altabajaPanelLayout.createSequentialGroup()
                                .addComponent(msSoloUnaOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 179, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        altabajaPanelLayout.setVerticalGroup(
            altabajaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altabajaPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(altabajaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carteraLabel)
                    .addComponent(carteraText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(altabajaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLabel)
                    .addComponent(numeroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(msNoParticipaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(altabajaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(altabajaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(altaCheckBox)
                        .addComponent(bajaCheckBox))
                    .addComponent(msSoloUnaOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(altabajaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aceptarButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(msjObligatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        participacionesPanel.addTab("alta / baja", altabajaPanel);

        btnSalir.setBackground(new java.awt.Color(180, 22, 45));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setLabel("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(participacionesPanel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(46, 46, 46)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(participacionesPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addGap(28, 28, 28))
        );

        participacionesPanel.getAccessibleContext().setAccessibleName("Compra / Venta");

        getAccessibleContext().setAccessibleName("altabajaPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void precioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTextActionPerformed

    private void nParticipacionesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nParticipacionesTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nParticipacionesTextActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void saldoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoTextActionPerformed

    private void carteraTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carteraTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carteraTextActionPerformed

    private void numeroTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTextActionPerformed

    private void bajaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bajaCheckBoxActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton aceptarButton1;
    private javax.swing.JCheckBox altaCheckBox;
    private javax.swing.JPanel altabajaPanel;
    private javax.swing.JCheckBox bajaCheckBox;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton buscarButton;
    private javax.swing.JLabel carteraLabel;
    private javax.swing.JTextField carteraText;
    private javax.swing.JLabel comisionLabel;
    private javax.swing.JTextField comisionText;
    private javax.swing.JPanel compraventaPanel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private java.awt.Label msNoParticipaciones;
    private java.awt.Label msSoloUnaOpcion;
    private java.awt.Label msjObligatorio;
    private javax.swing.JTextField nParticipacionesText;
    private javax.swing.JLabel nparticipacionesLabel;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField numeroText;
    private javax.swing.JTabbedPane participacionesPanel;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JTextField precioText;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JTextField saldoText;
    // End of variables declaration//GEN-END:variables
}
