package gui;

import aplicacion.TipoUsuario;
import aplicacion.EmpresaUsuario;
import java.awt.Color;

public class VUsuario extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;
    String id = null;
    int CheckeoUsuario;
    Color prueba = new Color(60, 63, 65);

    public VUsuario(aplicacion.FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();
        this.getContentPane().setBackground(prueba);
        obligatorioTexto.setEnabled(false);
        this.buscarUsuarios();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buscaId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buscaNombre = new javax.swing.JTextField();
        BotonBuscarUsuarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnNombre = new javax.swing.JTextField();
        btnMail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tipo_usr = new javax.swing.JComboBox();
        BtnNuevoUsuario = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnClave = new javax.swing.JPasswordField();
        obligatorio1 = new javax.swing.JLabel();
        obligatorio2 = new javax.swing.JLabel();
        obligatorio3 = new javax.swing.JLabel();
        obligatorio4 = new javax.swing.JLabel();
        obligatorioTexto = new javax.swing.JLabel();

        jButton4.setText("Guardar");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Usuarios");

        jLabel1.setText("id:");

        buscaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaIdActionPerformed(evt);
            }
        });

        jLabel2.setText("nombre:");

        buscaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaNombreActionPerformed(evt);
            }
        });

        BotonBuscarUsuarios.setText("Buscar");
        BotonBuscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarUsuariosActionPerformed(evt);
            }
        });

        TablaUsuarios.setModel(new ModeloTablaUsuarios());
        TablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsuarios);

        jLabel3.setText("id:");

        btnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre:");

        btnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreActionPerformed(evt);
            }
        });

        btnMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMailActionPerformed(evt);
            }
        });

        jLabel5.setText("clave:");

        jLabel6.setText("e-mail:");

        btnDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireccionActionPerformed(evt);
            }
        });

        jLabel7.setText("tipo:");

        jLabel8.setText("dirección:");

        tipo_usr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Administrador" }));
        tipo_usr.setAutoscrolls(true);
        tipo_usr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_usrActionPerformed(evt);
            }
        });

        BtnNuevoUsuario.setText("Nuevo");
        BtnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoUsuarioActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(180, 22, 45));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaveActionPerformed(evt);
            }
        });

        obligatorio1.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio1.setText("*");

        obligatorio2.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio2.setText("*");

        obligatorio3.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio3.setText("*");

        obligatorio4.setForeground(new java.awt.Color(255, 0, 0));
        obligatorio4.setText("*");

        obligatorioTexto.setForeground(new java.awt.Color(255, 0, 0));
        obligatorioTexto.setText("Rellena los campos obligatorios *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obligatorioTexto)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(obligatorio3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(buscaId)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotonBuscarUsuarios))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 .addGroup(layout.createSequentialGroup()
     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
         .addComponent(jLabel4)
         .addGroup(layout.createSequentialGroup()
             .addComponent(obligatorio1)
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(jLabel3)))
     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
         .addComponent(btnNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
         .addComponent(btnID))
     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
             .addGap(69, 69, 69)
             .addComponent(obligatorio2))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(obligatorio4)))
     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
             .addComponent(jLabel5))
         .addGroup(layout.createSequentialGroup()
             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
             .addComponent(jLabel6))))
 .addGroup(layout.createSequentialGroup()
     .addComponent(BtnNuevoUsuario)
     .addGap(46, 46, 46)
     .addComponent(btnGuardar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
 .addComponent(btnBorrar)
 .addComponent(btnMail, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
 .addComponent(btnClave))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
 .addGroup(layout.createSequentialGroup()
     .addComponent(jLabel7)
     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
     .addComponent(tipo_usr, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
 .addGroup(layout.createSequentialGroup()
     .addComponent(jLabel8)
     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
     .addComponent(btnDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
 .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(buscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscarUsuarios))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(obligatorioTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obligatorio1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btnNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obligatorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tipo_usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btnDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(btnClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obligatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(btnMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obligatorio4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnNuevoUsuario)
                    .addComponent(btnSalir)
                    .addComponent(btnBorrar)
                    .addComponent(btnGuardar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        tipo_usr.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaIdActionPerformed

    private void buscaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaNombreActionPerformed

    private void btnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDActionPerformed

    }//GEN-LAST:event_btnIDActionPerformed

    private void btnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreActionPerformed

    }//GEN-LAST:event_btnNombreActionPerformed

    private void btnMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMailActionPerformed

    private void btnDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDireccionActionPerformed

    private void tipo_usrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_usrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_usrActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void BotonBuscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarUsuariosActionPerformed
        this.buscarUsuarios();
    }//GEN-LAST:event_BotonBuscarUsuariosActionPerformed

    private void BtnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoUsuarioActionPerformed
        id = null;
        btnID.setText("");
        btnClave.setText("");
        btnNombre.setText("");
        btnDireccion.setText("");
        btnMail.setText("");
        tipo_usr.setSelectedIndex(0);
        btnBorrar.setEnabled(true);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_BtnNuevoUsuarioActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ModeloTablaUsuarios m;
        m = (ModeloTablaUsuarios) TablaUsuarios.getModel();

        if (btnID.getText().equals("")) {
            obligatorioTexto.setEnabled(true);
        } else {
            obligatorio1.setEnabled(false);
        }
        if (btnNombre.getText().equals("")) {
            obligatorioTexto.setEnabled(true);
        } else {
            obligatorio3.setEnabled(false);
        }
        if (btnClave.getText().equals("")) {
            obligatorioTexto.setEnabled(true);
        } else {
            obligatorio2.setEnabled(false);
        }
        if (btnMail.getText().equals("")) {
            obligatorioTexto.setEnabled(true);
        } else {
            obligatorio4.setEnabled(false);
        }

        if (!btnID.getText().equals("") && !btnNombre.getText().equals("")
                && !btnClave.getText().equals("") && !btnMail.getText().equals("")) {
            obligatorioTexto.setEnabled(false);
        }
        if (obligatorioTexto.isEnabled()) {
            return;
        }
        EmpresaUsuario u;
        u = new EmpresaUsuario(btnID.getText(), btnClave.getText(), btnNombre.getText(), btnDireccion.getText(),
                btnMail.getText(), TipoUsuario.valueOf(tipo_usr.getSelectedItem().toString()));
        if (m.obtenerId().contains(u.getIdUsuario())) {
            id = u.getIdUsuario();
        }
        //fa.actualizarUsuario(u, id);  //Comentado para que no de error

        this.buscarUsuarios();
        this.BtnNuevoUsuarioActionPerformed(evt);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void TablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsuariosMouseClicked
        /*ModeloTablaUsuarios m;    //Comentado por ahora, para que no de error
        EmpresaUsuario u;
        m = (ModeloTablaUsuarios) TablaUsuarios.getModel();
        u = m.obtenerUsuario(TablaUsuarios.getSelectedRow());
        btnID.setText(u.getIdUsuario());
        btnClave.setText(u.getClave());
        btnNombre.setText(u.getNombre());
        btnDireccion.setText(u.getDireccion());
        btnMail.setText(u.getEmail());
        tipo_usr.setSelectedItem(u.getTipoUsuario().toString());
        id = u.getIdUsuario();*/
    }//GEN-LAST:event_TablaUsuariosMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        /*ModeloTablaUsuarios m;        //Comentado para que no de error
        EmpresaUsuario u;
        m = (ModeloTablaUsuarios) TablaUsuarios.getModel();
        u = m.obtenerUsuario(TablaUsuarios.getSelectedRow());
        fa.borrarUsuario(u.getIdUsuario());
        this.buscarUsuarios();*/
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarUsuarios;
    private javax.swing.JButton BtnNuevoUsuario;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JPasswordField btnClave;
    private javax.swing.JTextField btnDireccion;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField btnID;
    private javax.swing.JTextField btnMail;
    private javax.swing.JTextField btnNombre;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField buscaId;
    private javax.swing.JTextField buscaNombre;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel obligatorio1;
    private javax.swing.JLabel obligatorio2;
    private javax.swing.JLabel obligatorio3;
    private javax.swing.JLabel obligatorio4;
    private javax.swing.JLabel obligatorioTexto;
    private javax.swing.JComboBox tipo_usr;
    // End of variables declaration//GEN-END:variables

    public void buscarUsuarios() {
        ModeloTablaUsuarios m;

        m = (ModeloTablaUsuarios) TablaUsuarios.getModel();
        //m.setFilas(fa.obtenerUsuarios(buscaId.getText(), buscaNombre.getText()));     //Comentado para que no de error
        if (m.getRowCount() > 0) {
            TablaUsuarios.setRowSelectionInterval(0, 0);
            btnBorrar.setEnabled(true);
        } else {
            btnBorrar.setEnabled(false);
        }

    }
}
